server:
  port: 8001

eureka:
  instance:
    # 主机名
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # Eureka服务端地址，客户端使用该地址与Eureka进行通信(Eureka Server的地址)
      defaultZone: http://localhost:8761/eureka
      # 集群
      # defaultZone: http://eurekaOne:8761/eureka,http://eurekaTow:8762/eureka
    # 是否将自己的路径注册到Eureka(服务的提供方才需要注册到Eureka)[默认为 true 可省略]
    register-with-eureka: true
    # 是否需要再Eureka中抓取路径（服务的调用方需要）[默认为 true 可省略]
    fetch-registry: true
spring:
  application:
    # 对应Eureka web控制台Instances currently registered with Eureka 中 Application 显示的名称
    # 将来使用该名称获取对应访问的路径
    name: providerClient