server:
  # Eureka默认端口也是8761
  port: 8761
# 配置Eureka
# Eureka共四部分配置
# 1. dashboard  : Eureka的Web控制台相关配置
# 2. server     : 服务端相关配置
# 3. instance   : 实例[项目]相关配置
eureka:
  instance:
    # 主机名(单机环境下搭建集群，主机名不可相同（主机名相同无法构成集群）)
    hostname: eurekaOne
  client:
    service-url:
      # Eureka服务端地址，客户端使用该地址与Eureka进行通信
      defaultZone: http://eurekaTow:8762/eureka
    # 是否将自己的路径注册到Eureka(服务的提供方才需要注册到Eureka)
    register-with-eureka: true
    # 是否需要再Eureka中抓取路径（服务的调用方需要）
    fetch-registry: true
spring:
  application:
    name: eurekaColony

